name = "instagram"
main = "src/worker/index.ts"
compatibility_date = "2024-09-01"

[vars]
# Environment variables
# NODE_ENV = "production"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "d1database"
database_id = "ff4ca6de-8b86-4a90-a029-47f7f42f53dd"
